services:
  app:
    container_name: pintrail-app
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        progress: plain
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    restart: on-failure:0
    networks:
      - web
    ports:
      - 3000:3000
    depends_on:
      - forefront-olympus
      - forefront-hermes
networks:
  web:
    driver: bridge
