services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP Port
      - "80:80"
      # The Traefik Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So Traefik can listen to Docker Events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`yourdomain.com`)" # Replace with your domain or IP
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000" # Vite app port inside the container
    networks:
      - web
networks:
  web:
    driver: bridge
