FROM node:20.17.0-alpine as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

# FROM ubuntu
# RUN apt-get update
# RUN apt-get install nginx -y
# COPY --from=build /app/dist /var/www/html/
# EXPOSE 443
# CMD ["nginx","-g","daemon off;"]