version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs
    # Optionally, you can add volume mounts for logs or configuration
    # volumes:
    #   - ./logs:/app/logs
