version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "80:80"
      # The Traefik Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So Traefik can listen to Docker Events
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
